#!/bin/sh
### BEGIN INIT INFO
# Provides:          boomerang-express
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     -
# Default-Stop:      -
# Short-Description: Beacon reciever service
# Description:       boomerang-express beacon reciever service
### END INIT INFO
# chkconfig:         - 80 20

# Author: Andreas Marschke <andreas.marschke@gmail.com>

# Do NOT "set -e"

LOG_DIR="/var/log"

# Path where boomerang-express is installed
APP_PATH="/opt/boomerang-express"

# STDERR to file:
STDERR="$LOG_DIR/boomerang-express.err"

# STDOUT to file: 
STDOUT="$LOG_DIR/boomerang-express.log"

# forever logs to:
LOG="$LOG_DIR/boomerang-express.forever"

# basepath for pids etc.:
BASEPATH="/var/run"

# pidfile is saved at: 
PIDFILE="$BASEPATH/boomerang-express.pid"

LOCKFILE="/var/lock/subsys/boomerang-express"

# Max retries: 
MAX=3

# minUptime
MINUPTIME="100ms"

# spinSleepTime
SPINSLEEPTIME="1000ms"

EXTRA_ARGS="--append --no-colors"

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="NodeJS: Boomerang-Express - logs away boomerang GET requests"
NAME=boomerang-express
SCRIPTNAME=/etc/init.d/$NAME

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON=$APP_PATH/node_modules/forever/bin/forever

do_start() {
    
    if [ -e $LOCKFILE ]; then 
	echo "Warning! Lockfile exists!"
	return 1
    fi

    $DAEMON start -m $MAX -l $LOG -o $STDOUT -e $STDERR -p $BASEPATH --pidFile $PIDFILE --minUptime $MINUPTIME --spinSleepTime $SPINSLEEPTIME $EXTRA_ARGS $APP_PATH/app.js || retval = $?
    
    if [ ! -e $LOCKFILE ] && [ ! "$retval" = 1 ]; then
	touch $LOCKFILE
    fi
}

do_stop() {

    $DAEMON stop -m $MAX -l $LOG -o $STDOUT -e $STDERR -p $BASEPATH --pidFile $PIDFILE  --minUptime $MINUPTIME --spinSleepTime $SPINSLEEPTIME $EXTRA_ARGS $APP_PATH/app.js || retval = $?

    if [ -e $LOCKFILE ] && [ ! "$retval" =  1 ]; then
	rm $LOCKFILE
    fi
}

do_restart() {
    if [ -e $LOCKFILE ]; then
	rm $LOCKFILE
    fi

    $DAEMON restart -m $MAX -l $LOG -o $STDOUT -e $STDERR -p $BASEPATH --pidFile $PIDFILE  --minUptime $MINUPTIME --spinSleepTime $SPINSLEEPTIME $EXTRA_ARGS $APP_PATH/app.js || retval = $?
    
    if [ ! -e $LOCKFILE ] && [ ! "$retval" = "1" ]; then
	touch $LOCKFILE
    fi
}

do_list() {
    $DAEMON list || return 1
}

case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart)
	do_restart
	;;
    list)
	do_list
	;;
    status)
	do_list
	;;
    reload)
	do_restart
	;;
    *)
	echo "Usage: $SCRIPTNAME {start|stop|stopall|restart|restartall|list|reload|status}" >&2
	;;
esac

:

